castelo/urls.py
from django.urls import path
from . import views

app_name = 'castelo'
urlpatterns = [
    path('', views.castelo, name='home'),  # home
    path('casas/', views.casas, name='casas'),  # casas
]

corvinal/urls.py
from django.urls import path
from . import views

app_name = 'corvinal'
urlpatterns = [
    path('', views.salao_comunal, name='salao_comunal'),  # home
    path('sobre', views.sobre, name='sobre'),  # sobre
    path('membros', views.membros, name='membros'),  # membros
    path('quadribol', views.quadribol, name='quadribol'),  # quadribol
    path('quadribol/trofeu/<int:id>', views.trofeu, name='trofeu'),  # quadribol
]

grifinoria/urls.py
from django.urls import path
from . import views

app_name = 'grifinoria'
urlpatterns = [
    path('', views.salao_comunal, name='salao_comunal'),  # home
    path('sobre', views.sobre, name='sobre'),  # sobre
    path('membros', views.membros, name='membros'),  # membros
    path('quadribol', views.quadribol, name='quadribol'),  # quadribol
    path('quadribol/trofeu/<int:id>', views.trofeu, name='trofeu'),  # quadribol
]

hogwarts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('castelo.urls')),
    path('grifinoria/', include('grifinoria.urls')),
    path('sonserina/', include('sonserina.urls')),
    path('lufalufa/', include('lufalufa.urls')),
    path('corvinal/', include('corvinal.urls')),
]

lufalufa/urls.py
from django.urls import path
from . import views

app_name = 'lufalufa'
urlpatterns = [
    path('', views.salao_comunal, name='salao_comunal'),  # home
    path('sobre', views.sobre, name='sobre'),  # sobre
    path('membros', views.membros, name='membros'),  # membros
    path('quadribol', views.quadribol, name='quadribol'),  # quadribol
    path('quadribol/trofeu/<int:id>', views.trofeu, name='trofeu'),  # quadribol
]

sonserina/urls.py
from django.urls import path
from . import views

app_name = 'sonserina'
urlpatterns = [
    path('', views.salao_comunal, name='salao_comunal'),  # home
    path('sobre', views.sobre, name='sobre'),  # sobre
    path('membros', views.membros, name='membros'),  # membros
    path('quadribol', views.quadribol, name='quadribol'),  # quadribol
    path('quadribol/trofeu/<int:id>', views.trofeu, name='trofeu'),  # quadribol
]

castelo/models.py
from django.db import models

# Create your models here.

corvinal/models.py
from django.db import models

# Create your models here.

grifinoria/models.py
from django.db import models

# Create your models here.

lufalufa/models.py
from django.db import models

# Create your models here.

sonserina/models.py
from django.db import models

# Create your models here.

castelo/views.py
from django.shortcuts import render

# Create your views here.


def castelo(request):
    return render(request, 'castelo/pages/castelo.html')


def casas(request):
    return render(request, 'castelo/pages/casas.html')

corvinal/views.py
from django.shortcuts import render
import fabrica

# Create your views here.


def salao_comunal(request):
    return render(request, 'corvinal/pages/corvinal.html')


def sobre(request):
    return render(request, 'corvinal/pages/sobre_corvinal.html')


def membros(request):
    return render(request, 'corvinal/pages/membros_corvinal.html')


def quadribol(request):
    return render(request, 'corvinal/pages/quadribol_corvinal.html', context={'trofeus': lista_vitorias})


lista_vitorias = [fabrica.jogo_corvinal() for _ in range(10)]


def trofeu(request, id):
    for item in lista_vitorias:
        if item['ano'] == id:
            vitoria = item
            break
    return render(request, 'corvinal/pages/trofeu.html',
                  context={'vitoria': vitoria})

grifinoria/views.py
from django.shortcuts import render
import fabrica

# Create your views here.


def salao_comunal(request):
    return render(request, 'grifinoria/pages/grifinoria.html')


def sobre(request):
    return render(request, 'grifinoria/pages/sobre_grifinoria.html')


def membros(request):
    return render(request, 'grifinoria/pages/membros_grifinoria.html')


def quadribol(request):
    return render(request, 'grifinoria/pages/quadribol_grifinoria.html', context={'trofeus': lista_vitorias})


lista_vitorias = [fabrica.jogo_grifinoria() for _ in range(10)]


def trofeu(request, id):
    for item in lista_vitorias:
        if item['ano'] == id:
            vitoria = item
            break
    return render(request, 'grifinoria/pages/trofeu.html',
                  context={'vitoria': vitoria})

lufalufa/views.py
from django.shortcuts import render
import fabrica

# Create your views here.


def salao_comunal(request):
    return render(request, 'lufalufa/pages/lufalufa.html')


def sobre(request):
    return render(request, 'lufalufa/pages/sobre_lufalufa.html')


def membros(request):
    return render(request, 'lufalufa/pages/membros_lufalufa.html')


def quadribol(request):
    return render(request, 'lufalufa/pages/quadribol_lufalufa.html', context={'trofeus': lista_vitorias})


lista_vitorias = [fabrica.jogo_lufalufa() for _ in range(10)]


def trofeu(request, id):
    for item in lista_vitorias:
        if item['ano'] == id:
            vitoria = item
            break
    return render(request, 'lufalufa/pages/trofeu.html',
                  context={'vitoria': vitoria})

sonserina/views.py
from django.shortcuts import render
import fabrica

# Create your views here.


def salao_comunal(request):
    return render(request, 'sonserina/pages/sonserina.html')


def sobre(request):
    return render(request, 'sonserina/pages/sobre_sonserina.html')


def membros(request):
    return render(request, 'sonserina/pages/membros_sonserina.html')


def quadribol(request):
    return render(request, 'sonserina/pages/quadribol_sonserina.html', context={'trofeus': lista_vitorias})


lista_vitorias = [fabrica.jogo_sonserina() for _ in range(10)]


def trofeu(request, id):
    for item in lista_vitorias:
        if item['ano'] == id:
            vitoria = item
            break
    return render(request, 'sonserina/pages/trofeu.html',
                  context={'vitoria': vitoria})

castelo/templates/castelo/pages/casas.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Casas{% endblock titulo%}{% block main %} {% load static %} <main>
    <!-- SECTION DIVIDER -->
    <div class="section-divider container">
        <div class="section-divider-border"></div>
        <img src="{% static '/global/imgs/global/harry-potter-icon.png' %}" class="divider-icon">
        <div class="section-divider-border"></div>
    </div>
    <div class="section-image">
        <img id="salao" src="{% static '/global/imgs/global/salao.jpg' %}" alt="welcome">
    </div>
    <!-- SECTION: HOUSES -->
    <section class="section container" id="section-houses">
        <p> Os estudantes de magia e bruxaria da franquia Harry Potter, universo criado por J.K. Rowling, são divididos em quatro grupos bem distintos, as quatro casas de Hogwarts. Elas são: </p>
        <div class="infos">
            <h2>Casas de Hogwards</h2>
            <div class="title-divider-vertical"></div>
            <div class="houses">
                <!-- Grifinória -->
                <div class="card" id="grifinoria">
                    <div class="card-info">
                        <h3>Grifinória</h3>
                        <img src="{% static '/global/imgs/grifinoria/brasao.png' %}" alt="Grifinória">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, quis deserunt facere obcaecati rem sed id, reprehenderit repellat, aut ea accusamus ipsam voluptate praesentium vero exercitationem! Iure impedit quae placeat! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos dolorum iusto harum illo, ipsa deserunt blanditiis eveniet eaque maiores sit maxime ducimus quidem minus nihil unde, ipsam, quo tempora ea!</p>
                        <a href="">
                            <div class="button-wrapper">
                                <div class="button-detail button-detail-left"></div>
                                <button><a href="{% url 'grifinoria:salao_comunal' %}" style="color: white;"><span>Ver Casa</span></a></button>
                                <div class="button-detail button-detail-right"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <!-- Sonserina -->
                <div class="card" id="sonserina">
                    <div class="card-info">
                        <h3>Sonserina</h3>
                        <img src="{% static '/global/imgs/sonserina/brasao.png' %}" alt="Sonserina">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, quis deserunt facere obcaecati rem sed id, reprehenderit repellat, aut ea accusamus ipsam voluptate praesentium vero exercitationem! Iure impedit quae placeat! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos dolorum iusto harum illo, ipsa deserunt blanditiis eveniet eaque maiores sit maxime ducimus quidem minus nihil unde, ipsam, quo tempora ea!</p>
                        <a href="}">
                            <div class="button-wrapper">
                                <div class="button-detail button-detail-left"></div>
                                <button><a href="{% url 'sonserina:salao_comunal' %}" style="color: white;"><span>Ver Casa</span></a></button>
                                <div class="button-detail button-detail-right"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <!-- Corvinal -->
                <div class="card" id="corvinal">
                    <div class="card-info">
                        <h3>Corvinal</h3>
                        <img src="{% static '/global/imgs/corvinal/brasao.png' %}" alt="Corvinal">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, quis deserunt facere obcaecati rem sed id, reprehenderit repellat, aut ea accusamus ipsam voluptate praesentium vero exercitationem! Iure impedit quae placeat! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos dolorum iusto harum illo, ipsa deserunt blanditiis eveniet eaque maiores sit maxime ducimus quidem minus nihil unde, ipsam, quo tempora ea!</p>
                        <a href="">
                            <div class="button-wrapper">
                                <div class="button-detail button-detail-left"></div>
                                <button><a href="{% url 'corvinal:salao_comunal' %}" style="color: white;"><span>Ver Casa</span></a></button>
                                <div class="button-detail button-detail-right"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <!-- Lufa-Lufa -->
                <div class="card" id="lufa-lufa">
                    <div class="card-info">
                        <h3>Lufa-Lufa</h3>
                        <img src="{% static '/global/imgs/lufalufa/brasao.png' %}" alt="Lufa-Lufa">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, quis deserunt facere obcaecati rem sed id, reprehenderit repellat, aut ea accusamus ipsam voluptate praesentium vero exercitationem! Iure impedit quae placeat! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos dolorum iusto harum illo, ipsa deserunt blanditiis eveniet eaque maiores sit maxime ducimus quidem minus nihil unde, ipsam, quo tempora ea!</p>
                        <a href="">
                            <div class="button-wrapper">
                                <div class="button-detail button-detail-left"></div>
                                <button><a href="{% url 'lufalufa:salao_comunal' %}" style="color: white;"><span>Ver Casa</span></a></button>
                                <div class="button-detail button-detail-right"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main> {% endblock main %}

castelo/templates/castelo/pages/castelo.html
{% extends 'global/pages/base_home_casas.html' %} {% block img-botao %}{% load static %} <a class="nav-item" href="{% url 'castelo:casas' %}"><img id="logo" src="{% static '/global/imgs/global/selector-hat.png' %}" alt="Hogwarts"></a> {% endblock img-botao %} {% block main %} {% load static %} <main>
  <dv>
    <div class="button-wrapper">
      <div class="button-detail button-detail-left"></div>
      <button id="botao">
        <span><a href="{% url 'castelo:casas' %}">Bem vindo à</a></span>
      </button>
      <div class="button-detail button-detail-right"></div>
    </div>
    <section class="section container" id="section-hogwards">
      <h2>Hogwards</h2>
    </section>
  </dv>
  <div class="section-image">
    <img id="welcome" src="{% static '/global/imgs/global/welcome.png' %}" alt="welcome">
  </div>
  <!-- SECTION DIVIDER -->
  <div class="section-divider container">
    <div class="section-divider-border"></div>
    <img src="{% static '/global/imgs/global/harry-potter-icon.png' %}" class="divider-icon">
    <div class="section-divider-border"></div>
  </div>
  <!-- SECTION: BOOKS -->
  <section class="section container" id="section-books">
    <h2>Livros da Franquia</h2>
    <p> A ordem oficial para leitura dos livros não contém muito segredo, porque ela vai de acordo com os títulos lançados. O primeiro livro estreou em 1997 e desde então, o sucesso de Harry Potter só aumentou. </p>
    <table>
      <thead>
        <tr>
          <th class="align-left">Livro</th>
          <th class="align-right">Ano</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="align-left">Harry Potter e a Pedra Filosofal</td>
          <td class="align-right">1997</td>
        </tr>
        <tr>
          <td class="align-left">Harry Potter e a Câmara Secreta</td>
          <td class="align-right">1998</td>
        </tr>
        <tr>
          <td class="align-left">Harry Potter e o Prisioneiro de Azkaban</td>
          <td class="align-right">1999</td>
        </tr>
        <tr>
          <td class="align-left">Harry Potter e o Cálice de Fogo</td>
          <td class="align-right">2000</td>
        </tr>
        <tr>
          <td class="align-left">Harry Potter e a Ordem da Fênix</td>
          <td class="align-right">2003</td>
        </tr>
        <tr>
          <td class="align-left">Harry Potter e o Enigma do Príncipe</td>
          <td class="align-right">2005</td>
        </tr>
        <tr>
          <td class="align-left">Harry Potter e as Relíquias da Morte</td>
          <td class="align-right">2007</td>
        </tr>
      </tbody>
    </table>
  </section>
</main> {% endblock main %}

corvinal/templates/corvinal/pages/corvinal.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Corvinal{% endblock titulo%} {% block css_casa %}{% load static %}
<link rel="stylesheet" href="{% static 'corvinal/css/corvinal.css' %}"> {% endblock css_casa %} {% block menu_casa%} {% include 'corvinal/partials/menu-corvinal.html' %} {% endblock menu_casa %} {% block main %} {% load static %} <main class="blue">
    <!-- SECTION DIVIDER -->
    <div class="section-divider container">
        <div class="section-divider-border"></div>
        <img src="{% static '/global/imgs/global/harry-potter-icon.png' %}" class="divider-icon" style="margin-left: 50px;">
        <div class="section-divider-border"></div>
    </div>
    <div class="section-image">
        <h2 id="title-grif">Corvinal</h2>
        <img class="brasao" src="{% static '/global/imgs/corvinal/brasao.png' %}" style="height: 300px;" alt="brasao">
    </div>
    </div>
</main> {% endblock main %} {% block cor_logo %}<img src="{% static '/global/imgs/corvinal/logo-hp-blue.png' %}" alt="Harry Potter">{% endblock cor_logo %}

corvinal/templates/corvinal/pages/membros_corvinal.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Membros{% endblock titulo%} {% block css_casa %} {% load static %}
<link rel="stylesheet" href="{% static 'corvinal/css/corvinal.css' %}"> {% endblock css_casa %} {% block menu_casa%} {% include 'corvinal/partials/menu-corvinal.html' %} {% endblock menu_casa %} {% block main %} {% load static %} <main class="blue">
    <!-- SECTION MEMBERS -->
    <section>
        <h2 id="section-house-members" style="margin-left: 300px;">Principais Membros</h2>
        <p id="membros" style="margin-left: 300px;">Os principais membros da casa Corvinal são:</p>
        <img id="harry" style="border-radius: 50%; margin-left: 300px; width: 300px; height: 170px;" src="{% static 'corvinal/imgs/member_ravenclaw_01.jpg' %}" alt="Luna Lovegood">
        <img id="hermione" style="border-radius: 50%; width: 300px;" src="{% static 'corvinal/imgs/member_ravenclaw_02.jpg' %}" alt="Cho Chang">
        <img id="rony" style="border-radius: 50%; width: 300px;" src="{% static 'corvinal/imgs/member_ravenclaw_03.jpg' %}" alt="Sibila Trelawney">
        <div class="actions">
            <div class="button-wrapper">
                <div class="button-detail button-detail-left"></div>
                <button style="margin-left: 400px;">
                    <span>Luna Lovegood & Cho Chang & Sibila Trelawney</span>
                </button>
                <div class="button-detail button-detail-right"></div>
            </div>
        </div>
    </section>
</main> {% endblock main %} {% block cor_logo %}<img src="{% static '/global/imgs/corvinal/logo-hp-green.png' %}" alt="Harry Potter">{% endblock cor_logo %}

corvinal/templates/corvinal/pages/quadribol_corvinal.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Quadribol{% endblock titulo%} {% block css_casa %}{% load static %}
<link rel="stylesheet" href="{% static 'corvinal/css/corvinal.css' %}"> {% endblock css_casa %} {% block menu_casa%} {% include 'corvinal/partials/menu-corvinal.html' %} {% endblock menu_casa %} {% block main %} {% load static %} <main class="blue">
    <h2 id="title-grif">Vitórias no Quadribol</h2>
    <!-- SECTION DIVIDER -->
    <div class="section-divider container">
        <div class="section-divider-border" style="margin-left: 40px;"></div>
        <img src="{% static '/global/imgs/global/pomo.png' %}" class="divider-icon">
        <div class="section-divider-border"></div>
    </div>
    <div class="section-image">
        <img style="width: 20%; margin-left: 300px;" src="{% static '/global/imgs/global/vitoria.png' %}" alt="vitoria">
    </div>
    <ul style="position: absolute; left: 600px; top: 30%;">
        <li>Ano - Jogo:</li> {% for vitoria in trofeus %} <li><a style="color: white;" href="quadribol/trofeu/{{vitoria.ano}}">{{vitoria.ano}} - {{vitoria.jogo}}</a></li> {% endfor %}
    </ul>
</main> {% endblock main %} {% block cor_logo %}<img src="{% static '/global/imgs/corvinal/logo-hp-blue.png' %}" alt="Harry Potter">{% endblock cor_logo %}

corvinal/templates/corvinal/pages/sobre_corvinal.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Sobre{% endblock titulo%} {% block css_casa %} {% load static %}
<link rel="stylesheet" href="{% static 'corvinal/css/corvinal.css' %}"> {% endblock css_casa %} {% block menu_casa%} {% include 'corvinal/partials/menu-corvinal.html' %} {% endblock menu_casa %} {% block main %} {% load static %} <main class="blue">
    <!-- SECTION SELECTOR HAT QUOTE -->
    <section class="section container" id="selector-hat-quote">
        <p>"Ou será a velha e sábia Corvinal; A casa dos que têm a mente sempre <b>alerta</b>, onde os homens de <b>grande espírito e saber</b> sempre encontrarão <b>companheiros</b> seus iguais." - o chapéu seletor</p>
    </section>
    <div id="titulo-sobre">
        <h2>Características da Casa</h2>
    </div>
    <!-- SECTION HOUSE FEATURES -->
    <section class="section container" id="section-house-features">
        <p class="description">A casa Corvinal, ou também conhecida como Ravenclaw, foi fundada por Rowena Ravenclaw e possui as cores azul e bronze. A casa Corvinal possui as seguintes características:</p>
        <div class="house-features-container">
            <div class="card">
                <span class="feature">Elemento:</span>
                <span class="feature-value">Ar</span>
            </div>
            <div class="card" id="ghost">
                <span class="feature">Fantasma:</span>
                <span class="feature-value">Dama Cinzenta</span>
            </div>
            <div class="card">
                <span class="feature">Animal:</span>
                <span class="feature-value">Águia</span>
            </div>
        </div>
    </section>
</main>{% endblock main %} {% block cor_logo %}<img src="{% static '/global/imgs/corvinal/logo-hp-blue.png' %}" alt="Harry Potter">{% endblock cor_logo %}

corvinal/templates/corvinal/pages/trofeu.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Quadribol{% endblock titulo%} {% block css_casa %}{% load static %}
<link rel="stylesheet" href="{% static 'corvinal/css/corvinal.css' %}"> {% endblock css_casa %} {% block menu_casa%} {% include 'corvinal/partials/menu-corvinal.html' %} {% endblock menu_casa %} {% block main %} {% load static %} <main class="blue">
    <h2 id="title-grif" style="position: relative; left: 100px">Detalhes da Vitória da Corvinal:</h2>
    <!-- SECTION DIVIDER -->
    <div class="section-divider container">
        <div class="section-divider-border" style="margin-left: 40px;"></div>
        <img src="{% static '/global/imgs/global/pomo.png' %}" class="divider-icon">
        <div class="section-divider-border"></div>
    </div>
    <div class="section-image">
        <ul>
            <li style="position: relative; left: 300px;">{{vitoria.ano}} - {{vitoria.jogo}}</li>
            <li style="position: relative; left: 300px; padding-bottom: 10px;">{{vitoria.descricao}}</li>
            <li><img style="width: 15%; position: relative; left: 50%" src={{vitoria.foto}}></li>
        </ul>
    </div>
</main> {% endblock main %} {% block cor_logo %}<img src="{% static '/global/imgs/corvinal/logo-hp-blue.png' %}" alt="Harry Potter">{% endblock cor_logo %}

corvinal/templates/corvinal/partials/menu-corvinal.html
<aside id="menu-corvinal">
    <h3>Saiba mais</h3>
    <a href="{% url 'corvinal:sobre' %}">Sobre</a>
    <a href="{% url 'corvinal:membros' %}">Membros</a>
    <a href="{% url 'corvinal:quadribol' %}">Quadribol</a>
</aside>

grifinoria/templates/grifinoria/pages/grifinoria.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Grifinória{% endblock titulo%} {% block css_casa %}{% load static %}
<link rel="stylesheet" href="{% static 'grifinoria/css/grifinoria.css' %}"> {% endblock css_casa %} {% block menu_casa%} {% include 'grifinoria/partials/menu-grifinoria.html' %} {% endblock menu_casa %} {% block main %} {% load static %} <main class="red">
    <!-- SECTION DIVIDER -->
    <div class="section-divider container">
        <div class="section-divider-border"></div>
        <img src="{% static '/global/imgs/global/harry-potter-icon.png' %}" class="divider-icon">
        <div class="section-divider-border"></div>
    </div>
    <div class="section-image">
        <h2 id="title-grif">Grifinória</h2>
        <img class="brasao" src="{% static '/global/imgs/grifinoria/brasao.png' %}" alt="brasao">
    </div>
    </div>
</main> {% endblock main %} {% block cor_logo %}<img src="{% static '/global/imgs/grifinoria/logo-hp-red.png' %}" alt="Harry Potter">{% endblock cor_logo %}

grifinoria/templates/grifinoria/pages/membros_grifinoria.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Membros{% endblock titulo%} {% block css_casa %} {% load static %}
<link rel="stylesheet" href="{% static 'grifinoria/css/grifinoria.css' %}"> {% endblock css_casa %} {% block menu_casa%} {% include 'grifinoria/partials/menu-grifinoria.html' %} {% endblock menu_casa %} {% block main %} {% load static %} <main class="red">
    <!-- SECTION MEMBERS -->
    <section>
        <h2 id="section-house-members" style="margin-left: 300px;">Principais Membros</h2>
        <p id="membros" style="margin-left: 300px;">Os principais membros da casa Grifinória são:</p>
        <img id="harry" style="border-radius: 50%; margin-left: 300px;" src="{% static 'grifinoria/imgs/member_gryffindor_01.jpg' %}" alt="Harry Potter">
        <img id="hermione" style="border-radius: 50%;" src="{% static 'grifinoria/imgs/member_gryffindor_02.jpg' %}" alt="Hermione Granger">
        <img id="rony" style="border-radius: 50%; width: 25%;" src="{% static 'grifinoria/imgs/member_gryffindor_03.jpg' %}" alt="Ron Wesley">
        <div class="actions">
            <div class="button-wrapper">
                <div class="button-detail button-detail-left"></div>
                <button style="margin-left: 400px;">
                    <span>Harry Potter & Hermione Granger & Rony Weasley</span>
                </button>
                <div class="button-detail button-detail-right"></div>
            </div>
        </div>
    </section>
</main> {% endblock main %} {% block cor_logo %}<img src="{% static '/global/imgs/grifinoria/logo-hp-red.png' %}" alt="Harry Potter">{% endblock cor_logo %}

grifinoria/templates/grifinoria/pages/quadribol_grifinoria.html
{% extends 'global/pages/base_home_casas.html' %} {% block titulo %}Quadribol{% endblock titulo%} {% block css_casa %}{% load static %}
<link rel="stylesheet" href="{% static 'grifinoria/css/grifinoria.css' %}"> {% endblock css_casa %} {% block menu_casa%} {% include 'grifinoria/partials/menu-grifinoria.html' %} {% endblock menu_casa %} {% block main %} {% load static %} <main class="red">
    <h2 id="title-grif">Vitórias no Quadribol</h2>
    <!-- SECTION DIVIDER -->
    <div class="section-divider container">
        <div class="section-divider-border" style="margin-left: 40px;"></div>
        <img src="{% static '/global/imgs/global/pomo.png' %}" class="divider-icon">
        <div class="section-divider-border"></div>
    </div>
    <div class="section-image">
        <img style="width: 20%; margin-left: 300px;" src="{% static '/global/imgs/grifinoria/vitoria.jpg' %}" alt="vitoria">
    </div>
    <ul style="position: absolute; left: 600px; top: 30%;">
        <li>Ano - Jogo:</li> {% for vitoria in trofeus %} <li><a style="color: white;" href="quadribol/trofeu/{{vitoria.ano}}">{{vitoria.ano}} - {{vitoria.jogo}}</a></li> {% endfor %}
    </ul>
</main> {% endblock main %} {% block cor_logo %}<img src="{% static '/global/imgs/grifinoria/logo-hp-red.png' %}" alt="Harry Potter">{% endblock cor_logo %}

grifinoria/templates/grifinoria/partials/menu-grifinoria.html
<aside id="menu-grifinoria">
    <h3>Saiba mais</h3>
    <a href="{% url 'grifinoria:sobre' %}">Sobre</a>
    <a href="{% url 'grifinoria:membros' %}">Membros</a>
    <a href="{% url 'grifinoria:quadribol' %}">Quadribol</a>
</aside>

lufalufa/templates/lufalufa/partials/menu-lufalufa.html
<aside id="menu-lufalufa">
    <h3>Saiba mais</h3>
    <a href="{% url 'lufalufa:sobre' %}">Sobre</a>
    <a href="{% url 'lufalufa:membros' %}">Membros</a>
    <a href="{% url 'lufalufa:quadribol' %}">Quadribol</a>
</aside>

sonserina/templates/sonserina/partials/menu-sonserina.html
<aside id="menu-sonserina">
    <h3>Saiba mais</h3>
    <a href="{% url 'sonserina:sobre' %}">Sobre</a>
    <a href="{% url 'sonserina:membros' %}">Membros</a>
    <a href="{% url 'sonserina:quadribol' %}">Quadribol</a>
</aside>